version: 0.{build}

branches:
  except:
    - gh-pages
    - docs

clone_depth: 3

environment:
  global:
    GITHUB_NAME: mmtouch

  matrix:
    - image: macos-monterey
      configuration: debug
    - image: macos-bigsur
      configuration: release

install:
  - xcodebuild -version

before_build:
  - env

build_script:
  - tree -L 3 ${pwd}
