version: 0.{build}

branches:
  except:
    - gh-pages
    - docs

clone_depth: 3

image: macos-monterey

environment:
  global:
    GITHUB_NAME: mmtouch

  matrix:
    - configuration: debug
    - image: Ubuntu
      configuration: debug

install:
  - ps: 

before_build:
  - env

build_script:
  - tree -L 3 ${pwd}
