version: 0.{build}

branches:
  except:
    - gh-pages
    - docs
    
image: macos

clone_depth: 3

environment:
  GITHUB_NAME: mmtouch
  
install:
  - brew install tree
  
configuration:
  - Release
  - debug

before_build:
  - env

build_script:
  - tree -L 3 ${pwd}
